### ISSUE TITLE
How to actually install this?

### ISSUE THREAD

**Issue by d33tah** [vkrasnov/dictator#10]
Sorry if there is an obvious answer, but I tried `go get github.com/vkrasnov/dictator` and instead of installing a command in $GOPATH/bin, it only built `/home/d33tah/GOPATH/pkg/linux_amd64/github.com/vkrasnov/dictator.a`. What am I doing wrong?

**Comment by vkrasnov** [comment]
Try `go install github.com/vkrasnov/dictator/cmd`

**Comment by d33tah** [comment]
@vkrasnov Thanks, that installed it as "cmd". If I might have a suggestion, renaming the binary name to "dictator" could be helpful :) Anyway, on my side, the issue can be closed.

Thanks!

**Comment by nazar-pc** [comment]
Maybe add a readme with simple instructions?
