### ISSUE TITLE
dictator's output is empty. 

### ISSUE THREAD

**Issue by yangxiaomin08** [vkrasnov/dictator#8]
hi,

I have tried to generate a dictionary for a web html file, but the result is empty as you can see the size of out file is 0 byte.  Does anyone knows why? Plus, I have another question, can the dictionary generated (if success) be used in brotli? thanks.  

$ go run dictator.go -in src.html.orig -out src.html.dict
100%  
Total incompressible strings found:  0
 $ ls -l
total 72
   1403 5月  19 15:56 dictator.go
   0 5月  19 16:08 src.html.dict
  65889 5月  19 15:50 src.html.orig

**Comment by vkrasnov** [comment]
Hi,

> go run dictator.go -in src.html.orig -out src.html.dict

You have to specify a folder, not a single file. If you must generate a dictionary for one file, create a directory that contains that file.

> can the dictionary generated (if success) be used in brotli? thanks.

No, it is incompatible with brotli, and brotli contains a built in dictionary. This dictionary is only for deflate.

**Comment by hatstand** [comment]
The dictionaries generated actually work reasonably well for brotli although they're not optimal.

**Comment by yangxiaomin08** [comment]
Great thanks. Vkrasnov. It did work after I put it in a folder.

**Comment by yangxiaomin08** [comment]
hi hatstand,

The dictionary in brotli looks like a hash  table, which is quite different with this script generated. Do you have any suggestion about how to use it?

**Comment by hatstand** [comment]
It's not a hash table, it's just a bunch of bytes, the same as the output of dictator.
