### ISSUE TITLE
can I edit the dictionary manually?

### ISSUE THREAD

**Issue by yangxiaomin08** [vkrasnov/dictator#9]
hi,

Can I modify the generated dictionary manually? such as remove some unexpected words and add some into it?  As my understanding, the dictionary is just text file format.  

Another question is is the more high frequency words appear the topper in the dictionary file?

thanks.

**Comment by vkrasnov** [comment]
You sure can. However if a word is there, it is probably common in your data set.

The higher frequency words appear the last.

**Comment by yangxiaomin08** [comment]
thank you for quick response.

**Comment by yangxiaomin08** [comment]
hello,

One more question:  I used this tool to generate the dictionary from thousands of HTTP request headers, but I saw some keywords are repeated in the dictionary file. 
Such as "Connection: keep-alive", and some lines lead with "User-Agent: Mozilla/5.0 (Linux;  xxx", xxx is different but similar.    

Is this design intent?

**Comment by vkrasnov** [comment]
It is not the intent. The algorithm will check if a given string is already in the dictionary, before adding it. So if there is even a single character difference, it will go in.

It would probably be a nice optimization to check for the longest substring already in the dictionary, and give a lower score to a string if part of it can be matched.
